# Generated by Django 2.2.3 on 2019-07-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qaafila', '0004_comment_commenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='hashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
